---
title: "Discussion Section Week 2"
description: "Creating a visual from drought data"
author: "Sam Lance"
format:
  html:
    code-fold: true
    toc: true
    number-sections: true
    embed-resources: true
    theme: Lux
editor: visual
execute:
  echo: true
  message: false
  warning: false
---

## Data Cleaning Provided by Sam

```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(tidyverse)

#..........................import data...........................
drought <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-07-20/drought.csv')

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                            wrangle drought data                          ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean <- drought |>

  # select cols of interest & update names for clarity (as needed) ----
  select(date = valid_start, state_abb, drought_lvl, area_pct) |> 

  # add year, month & day cols using {lubridate} fxns ----
  # NOTE: this step isn't necessary for our plot, but I'm including as examples of how to extract different date elements from a object of class `Date` using {lubridate} ----
  mutate(year = year(date),
         month = month(date, label = TRUE, abbr = TRUE),
         day = day(date)) |>

  # add drought level conditions names ----
  mutate(drought_lvl_long = factor(drought_lvl,
                            levels = c("D4", "D3", "D2", "D1","D0", "None"),
                            labels = c("(D4) Exceptional", "(D3) Extreme",
                                       "(D2) Severe", "(D1) Moderate", 
                                       "(D0) Abnormally Dry", 
                                       "No Drought"))) |>
  
  # reorder cols ----
  relocate(date, year, month, day, state_abb, drought_lvl, drought_lvl_long, area_pct)
```

## Creating Stacked Area Plot

```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##       create stacked area plot of CA drought conditions through time     ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean |> 
  
  # remove drought_lvl "None" & filter for just CA ----
  filter(drought_lvl != "None",
         state_abb == "CA") |> 
  ggplot(aes(x= date, y= area_pct, group= drought_lvl_long, fill = drought_lvl_long)) +
  labs(x = NULL, y = NULL, title = "Drought Area in California") + #sets the x and y labels 
  geom_area(position = position_stack(reverse = TRUE)) + #how we order our drought from D1-D4
  theme_minimal() +
  scale_fill_manual(values = c("#853904", "#FF0000", "#FFC100", "#FFD965", "#FFFF00")) +
  scale_x_date(date_labels = "%Y", #label by year
               breaks = scales::breaks_pretty(n=10), #set 10 braks
               expand = c(0, 0)) + #expand across the x axis 
  scale_y_continuous(breaks = seq(0, 100, 10), #breaks by series of 10 1-100
                     labels = scales::label_percent(scale = 1), #set the scale to say it goes up to 100%
                     expand = c(0,0)) + #expand to the y axis
  theme(
    #update axis lines + ticks
    axis.line = element_line(color = "#5A9CD6"),
    axis.ticks = element_line(color = "#5A9CD6"),
    
    #adjust lengths of axis ticks
    axis.ticks.length = unit(.2, "cm"), #provide length of ticks and the unit we use
    
    #axis title
    axis.title = element_blank(),
    axis.text = element_text(color = "#686868", size = 12),
    
    #legend
    legend.position = "bottom", 
    legend.title = element_blank(), #gets rid of legend title
    legend.key.height = unit(.25, "cm"), #change size of boxes
    legend.key.width = unit(.4, "cm"),
    legend.text = element_text(color = "#686868", size = 12),
    
    #title
    plot.title = element_text(hjust = 0.5,
                              color = "#686868",
                              size = 20,
                              margin = margin(t=10, r =0, b=15, l =0 )), #want to center our title text + add color
    
    plot.background = element_rect(color = "#686868"),
    plot.margin = margin(t= 10, r=10, b=10, l=10)
    
    
  
  )
```
